---
title: "Cycling Analytics"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    theme: 
      version: 4
      bootswatch: flatly
---

```{r setup, include=FALSE}
libs <- c("flexdashboard","tidyverse","plotly","leaflet","leaflet.extras","lubridate","mapdata")
purrr::walk(libs, ~library(.,character.only = T))

source("db/db.R")

con <- connect_db()

#source("scraper_functions.R")
#source("runtime_helpers.R")

#only add fields to the data retrieval as they are confirmed needed
ytd_activity_streams <- dbGetQuery(
  con,
  "SELECT
    a.activity_id,
    a.start_date_local,
    s.latitude,
    s.longitude
   FROM
    cycling_platform_silver.activities a
   INNER JOIN cycling_platform_silver.activity_streams s
    ON a.activity_id = s.activity_id
   WHERE
    a.sport_type IN ('Ride','VirtualRide')
    AND YEAR(a.start_date_local) = YEAR(NOW())"
)

tbr_activity_streams <- dbGetQuery(
  con,
  "SELECT
    a.activity_id
   FROM
    cycling_platform_silver.activities a
   INNER JOIN cycling_platform_silver.activity_streams s
    ON a.activity_id = s.activity_id
   WHERE
    a.activity_name like '%tbr%'"
)

# Manage the edge case early in the year when no outside rides logged yet
if(nrow(ytd_activity_streams) > 0) {

  position_extremities <- ytd_activity_streams |> 
    mutate(extremity = case_when(latitude == max(latitude, na.rm = T) ~ "N",
                                 latitude == min(latitude, na.rm = T) ~ "S",
                                 longitude == max(longitude, na.rm = T) ~ "E",
                                 longitude == min(longitude, na.rm = T) ~ "W")) |> 
    filter(!is.na(extremity)) |> 
    tidygeocoder::reverse_geocode(long = longitude, lat = latitude, full_results = T) |> 
    bind_rows(tibble(village = NA_character_, # ensure the village and suburb columns are present
                     suburb = NA_character_))
    
} else {
  
  position_extremities <- tibble(extremity = c("N","S","E","W")) |> 
    mutate(latitude = NA,
           longitude = NA,
           village = "No outside rides YTD",
           suburb = "No outside rides YTD")
  
}

```

Summary
===================================== 

Row
-----------------------------------------------------------------------

### `r str_glue('Last refresh: {format(Sys.time(), "%H:%M")}<br>','Next refesh: {format(get_next_scraper_run(), "%H:%M")}'
)`

```{r}
valueBox(format(Sys.time(), "%d %b %y"), color = "#EDF0F1")
```

### `r str_glue('Miles this year<br>({get_ytd_values("distance_mi", ytd_stats)["pytd"]} pytd)')`

```{r}
get_ytd_valuebox("ytd_distance_mi", ytd_stats)
```

### `r str_glue('Projected miles this year<br>({get_ytd_values("ytd_predicted_distance_mi", ytd_stats)["pytd"]} pytd projected, {get_ytd_values("distance_mi", ytd_stats)["pyr"]} py total)')`

```{r}
get_ytd_valuebox("ytd_predicted_distance_mi", ytd_stats)
```

### `r str_glue('Tons this year<br>({get_ytd_values("tons", ytd_stats)["pytd"]} pytd, {get_ytd_values("tons", ytd_stats)["pyr"]} py total)')`

```{r}
get_ytd_valuebox("ytd_tons", ytd_stats)
```

### `r str_glue('Hours this year<br>({get_ytd_values("time_hr", ytd_stats)["pytd"]} pytd, {get_ytd_values("time_hr", ytd_stats)["pyr"]} py total)')`

```{r}
get_ytd_valuebox("ytd_time_hr", ytd_stats)
```

### `r str_glue('Longest ride this year (mi)<br>({get_ytd_values("longest_ride", ytd_stats)["pytd"]} pytd, {get_ytd_values("longest_ride", ytd_stats)["pyr"]} py max)')`

```{r}
get_ytd_valuebox("ytd_longest_ride", ytd_stats)
```

Row 
-----------------------------------------------------------------------

### `r str_glue("Miles (vs {year(Sys.Date()) - 1})")`

```{r}
draw_ytd_curve("ytd_distance_mi", ytd_stats)
```

### `r str_glue("Tons (vs {year(Sys.Date()) - 1})")`

```{r}
draw_ytd_curve("ytd_tons", ytd_stats)
```

Row 
-----------------------------------------------------------------------

### Critical Power (vs all-time peaks)

```{r}
draw_critical_metric_curve("power", con)
```

Map
===================================== 

Row
-----------------------------------------------------------------------

### Most Northerly

```{r}
get_coord_valuebox("N")
```

### Most Southerly

```{r}
get_coord_valuebox("S")
```

### Most Easterly

```{r}
get_coord_valuebox("E")
```

### Most Westerly

```{r}
get_coord_valuebox("W")
```

Row
-----------------------------------------------------------------------

### `r str_glue("{year(Sys.Date())} tracks")`

```{r}
draw_ytd_map(ytd_streams)
```


Peak Performances
===================================== 

Row
-----------------------------------------------------------------------

### Power

```{r}
draw_critical_metric_curve("power", con)
```

### Cadence

```{r}
draw_critical_metric_curve("cadence", con)
```

### Heart Rate

```{r}
draw_critical_metric_curve("heart rate", con)
```

tbr
===================================== 

Row
-----------------------------------------------------------------------

### tbr rides

```{r}
valueBox(nrow(tbr_activities), color = "#EDF0F1")
```

### Total tbr miles

```{r}

peaks_units |> filter(metric == "distance") |> mutate(value = sum(tbr_activities$distance) * multiplier, value = str_glue("{round(value, digits = 1)} {units}")) |> pull(value) |> valueBox(color = "#EDF0F1")

```

### Longest tbr ride

```{r}
peaks_units |> filter(metric == "distance") |> mutate(value = max(tbr_activities$distance) * multiplier, value = str_glue("{round(value, digits = 1)} {units}")) |> pull(value) |> valueBox(color = "#EDF0F1")
```

Row
-----------------------------------------------------------------------

### tbr tracks

```{r}
draw_map(tbr_streams)
```
